### ISSUE TITLE
Rijkshuisstijl, videos: Stijl doorontwikkelen voor FSA

### ISSUE THREAD

**Issue by bartjkdp** [Pleio/pleio_template#153]
- [ ] Video's toevoegen, reactieveld moeten ook mogelijk zijn bij video (Archief 2.0) -> #203 
- [ ] Zoekveld doorvoeren in Rijkshuisstijl -> #204 
- [ ] Duimpjes in plaats van hartjes -> #197

**Comment by bartjkdp** [comment]
Voor alle items zijn losse tickets aangemaakt.
